VeryGoodOpenSource/very_good_dart_cli

.github/workflows/generate_template.yaml
- ci: generate brick on push to main
=> ci: generate brick on push to main

.github/workflows/my_cli.yaml, my_cli/test/src/commands/update_command_test.dart
=> fix: analysis warning

README.md
- docs: remove utm tags from README
=> docs: remove utm tags from README

my_cli/lib/src/command_runner.dart, my_cli/test/src/command_runner_test.dart
fix: update alert to the user should suggest the update command
=> fix: update alert to the user should suggest the update command

README.md, my_cli/lib/src/command_runner.dart, my_cli/lib/src/commands/sample_command.dart, my_cli/lib/src/commands/update_command.dart, my_cli/pubspec.yaml, my_cli/test/src/command_runner_test.dart, my_cli/test/src/commands/sample_command_test.dart, my_cli/test/src/commands/update_command_test.dart
=> feat: support verbose logging

brick/CHANGELOG.md, brick/LICENSE, brick/README.md, brick/brick.yaml
- chore: update brick metadata
=> chore: update brick metadata

.github/dependabot.yaml, src/my_cli/.github/dependabot.yaml, src/my_cli/analysis_options.yaml, src/my_cli/pubspec.yaml
- feat: upgrade to Dart 2.18 and very_good_analysis 3.0.2
=> feat: upgrade to Dart 2.18, very_good_analysis 3.0.2, and dependabot

brick/CHANGELOG.md, brick/README.md, brick/brick.yaml
=> chore: v0.1.0

src/my_cli/analysis_options.yaml, src/my_cli/pubspec.yaml
- feat: very_good_analysis 3.1.0
=> feat: very_good_analysis 3.1.0

src/my_cli/lib/src/command_runner.dart, src/my_cli/lib/src/commands/update_command.dart, src/my_cli/test/src/command_runner_test.dart
fix: update prompt on update
Related: 
https://github.com/VeryGoodOpenSource/very_good_cli/issues/520
https://github.com/VeryGoodOpenSource/very_good_cli/issues/521
=> fix: update prompt on update

brick/hooks/pre_gen.dart, brick/hooks/pubspec.yaml, tool/brick_generator/main.dart
- docs: remove copyright header and license from generated code
=> docs: remove copyright header and license from generated code

brick/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{project_name.snakeCase()}}.yaml, src/my_cli/.github/workflows/my_cli.yaml, tool/generator/main.dart
Adds the concurrency group to the workflow yaml file.
=> feat: adding ci concurrency group to workflow

src/my_cli/lib/src/commands/update_command.dart, src/my_cli/pubspec.yaml, src/my_cli/test/src/command_runner_test.dart, src/my_cli/test/src/commands/sample_command_test.dart, src/my_cli/test/src/commands/update_command_test.dart
=> feat: upgrade to Dart 2.19

patches/pubspec_publish.patch
- fix: update patch to Dart 2.19
=> fix: update patch to Dart 2.19

.github/workflows/generate_template.yaml
- ci: update generate template to trigger on changes to patches
=> ci: update generate template to trigger on changes to patches

src/my_cli/analysis_options.yaml, src/my_cli/pubspec.yaml, src/my_cli/test/ensure_build_test.dart
- chore: upgrade to very_good_analysis 4.0.0
=> chore: upgrade to very_good_analysis 4.0.0

brick/CHANGELOG.md, brick/brick.yaml
=> chore: v0.3.1

src/my_cli/README.md, src/my_cli/test/src/commands/sample_command_test.dart
Fix typo optioon to option
Remove PubUpdater is useless in SampleCommandTest
=> test: remove unused PubUpdater

.github/cspell.json, .github/dependabot.yaml, .github/workflows/my_cli.yaml, src/my_cli/.github/ISSUE_TEMPLATE/ config.yml, src/my_cli/.github/ISSUE_TEMPLATE/bug_report.md, src/my_cli/.github/ISSUE_TEMPLATE/feature_request.md, src/my_cli/.github/PULL_REQUEST_TEMPLATE.md, src/my_cli/.github/cspell.json, src/my_cli/.github/workflows/my_cli.yaml
feat: update workflows, add spellcheck
=> feat: update workflows, add spellcheck

brick/CHANGELOG.md, brick/brick.yaml
=> chore: v0.3.2

patches/pubspec_publish.patch, src/my_cli/analysis_options.yaml, src/my_cli/pubspec.yaml, src/my_cli/test/ensure_build_test.dart
Support Dart SDK to 2.18.0 since VeryGoodCli supports 2.18.0 (see [this](https://github.com/VeryGoodOpenSource/very_good_cli/pull/679)).
=> chore: support dart sdk 2.18.0

brick/CHANGELOG.md, brick/brick.yaml
=> chore: v0.3.3

brick/brick.yaml, patches/pubspec_publish.patch, src/my_cli/analysis_options.yaml, src/my_cli/pubspec.yaml
Related to https://github.com/VeryGoodOpenSource/very_good_cli/issues/702.
=> feat!: bump min Dart SDK to 2.19.0

patches/pubspec_publish.patch, src/my_cli/analysis_options.yaml, src/my_cli/pubspec.yaml
feat: update very good analysis to v5 and fix patch
=> feat: update very good analysis to v5 and fix patch

brick/CHANGELOG.md, brick/brick.yaml
- feat: update very good analysis to v5 and fix patch
- feat:: bump Dart SDK to >=3.0.0 <4.0.0
=> chore: v0.5.0

brick/brick.yaml, src/my_cli/LICENSE, src/my_cli/analysis_options.yaml, src/my_cli/pubspec.yaml
=> chore: update analysis, and mason  

brick/CHANGELOG.md, brick/brick.yaml
chore: v0.5.1
- feat: upgrade to very_good_analysis ^5.1.0
=> chore: v0.5.1

.github/workflows/semantic_pull_request.yaml, .github/workflows/very_good_dart_cli.yaml
**READY**
Renames the "very_good_core" workflow name to "very_good_dart_cli" due to an obvious typo.
Renames the "ci" workflow name to "semantic_pull_request" for a more descriptive name.
=> ci: rename workflows
